#!/usr/bin/env sh

cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null

# the referenced result/bin/xmonad will always have ctime of 1970-01-01
# so we just test the symlink
if [[ xmonad.hs -ot ./xmonad-x86_64-linux ]]; then
  exit 0
fi

nix build
ln -rs --force result/bin/xmonad ./xmonad-x86_64-linux

