#!/bin/bash

# This file must be kept executable for the shell specified in the
# shellbang to take action. Otherwise it uses login shell to execute
# the file, to which this xsession may not be syntatically correct.

paths=(
    /home/shou/.asdf/shims
    /home/shou/.asdf/bin
    /home/shou/.cargo/bin
    /home/shou/.local/bin
    /home/shou/.elan/bin
    /home/shou/.cabal/bin
    /home/shou/.shell/bin
    /home/shou/.nix-profile/bin
    /home/shou/.local/share/pnpm
    /home/shou/.bun/bin
    /usr/local/bin
    /usr/local/sbin
    /usr/sbin
    /sbin
    /usr/bin
    /bin
)
export PATH="$(IFS=: ; echo "${paths[*]}")"

exec 2> ~/.xsession-errors > ~/.xsession-log

# xresources
[ -f ~/.Xresources ] && xrdb -merge ~/.Xresources

# turn off audible bell
xset b off

# automatically swap ctrl/capslock on pluggable keyboards
~/.xmonad/scripts/new-keyboard.sh
inputplug -0 --command ~/.xmonad/scripts/new-keyboard.sh &

# pointer configs
~/.xmonad/scripts/touchpad-natural-scroll.sh

# compatibility configs
export XDG_CURRENT_DESKTOP=GNOME
# See https://blog.ando.fyi/posts/diagnosing-an-unsual-wifi-issue/
export QT_BEARER_POLL_TIMEOUT=-1

# external monitor setup
command -v mons && mons -e right || true

# set wallpaper
feh --bg-fill ~/Pictures/wallpapers/ -zr

# hidpi setting for gtk 3 apps
export GDK_SCALE=2
export GDK_DPI_SCALE=0.5

# hidpi for QT apps
export QT_SCALE_FACTOR=2
export QT_FONT_DPI=96

# Fix blank Java apps
export _JAVA_AWT_WM_NONREPARENTING=1

# compositor
picom --daemon

# status bar
# polybar --reload default-bar &
# TODO: fix eww. sometimes it just won't start on boot.
eww open main-window &

# network manager applet
(sleep 1; nm-applet) &

# clipboard
copyq &
autocutsel -fork

# pulseaudio control
pasystray &

# usb drive automount
udiskie --smart-tray &

# sleep/lock settings:
# do not blank the screen. I use dpms for that purpose.
xset s noblank
# dim the screen after 5 minutes (dim.sh), then start screensaver
# ~2 minutes (lock) after that, before the screen turns off.
xset s 180 110
xss-lock -n ~/.local/bin/dim.sh \
         --transfer-sleep-lock -- \
         ~/.local/bin/lock &
# turn off screen/monitor/video signal after 5 mins of inactivity
xset dpms 0 0 300

# gnome keyring
export $(gnome-keyring-daemon --start)

# from now on, redirect stdout and stderr to these files so
# .xsession-errors/.xsession-logs only contain output from startup
exec 1>/tmp/xmonad.stdout 2>/tmp/xmonad.stderr

if [[ -z "$DBUS_SESSION_BUS_ADDRESS" ]]; then
	exec dbus-launch --exit-with-session xmonad
else
	exec xmonad
fi
